[project]
authors = ["izulin <izulin@gmail.com>"]
channels = ["conda-forge", "pip"]
description = "Add a short description here"
name = "ptyr"
platforms = ["osx-64"]
version = "0.1.0"

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
mypy = ">=1.15.0,<2"
ruff = ">=0.9.7,<0.10"
black = ">=25.1.0,<26"
flake8 = ">=7.1.2,<8"
flake8-type-checking = ">=3.0.0,<4"

[pypi-dependencies]
pygame-ce = ">=2.5.3, <3"

