[project]
authors = ["izulin <izulin@gmail.com>"]
channels = ["conda-forge", "pip"]
description = "Add a short description here"
name = "ptyr"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
black = ">=24.10.0,<25"
nuitka = ">=2.6.5,<3"

[pypi-dependencies]
pygame-ce = ">=2.5.3, <3"
